

const activities = [
    'Salam pagi di pintu kelas (senyum & sapa)',
    '“Check-in emosi” dengan kartu perasaan',
    'Berbagi cerita kebaikan hari ini',
    'Menulis surat terima kasih untuk petugas sekolah',
    'Membuat kartu ucapan untuk teman yang sakit',
    'Hari tanpa mengejek (anti-bullying day)',
    'Tukar tempat duduk untuk mengenal teman baru',
    'Mendengarkan cerita teman tanpa menyela',
    'Permainan “tebak perasaan” dari ekspresi',
    'Latihan memberi pujian yang tulus',
    'Membuat poster kata-kata baik',
    'Membaca buku tentang empati lalu diskusi',
    'Menjaga tanaman kelas bersama',
    'Menghemat air saat cuci tangan',
    'Mematikan lampu/AC saat tidak dipakai',
    'Bank sampah mini di kelas',
    'Membuat kerajinan dari barang bekas',
    'Hari bawa bekal sehat dan berbagi cerita',
    'Olahraga bersama dengan aturan fair play',
    'Menyusun aturan kelas bersama',
    'Menjadi “penjaga ketenangan” bergiliran',
    'Latihan meminta izin sebelum meminjam',
    'Menyusun jadwal tugas pribadi',
    'Membantu guru membagikan buku',
    'Menjadi “penyemangat” untuk teman yang gugup',
    'Membuat komitmen kelas (janji bersama)',
    'Menonton video pendek tentang kebaikan lalu refleksi',
    'Menulis daftar hal yang disyukuri',
    'Permainan kerja sama (misalnya estafet tim)',
    'Latihan menerima kekalahan dengan sportif',
    'Mengucapkan selamat kepada pemenang',
    'Membuat sudut baca nyaman untuk semua',
    'Bergiliran menjadi pemimpin doa',
    'Membantu merapikan alat belajar bersama',
    'Latihan berbicara jujur dalam situasi sulit',
    'Menghargai perbedaan (diskusi sederhana)',
    'Membuat “pohon kebaikan” di dinding kelas',
    'Mengumpulkan cerita inspiratif dari rumah',
    'Latihan menyapa orang dengan sopan',
    'Simulasi menolong orang yang membutuhkan',
    'Membuat aturan penggunaan gadget (jika ada)',
    'Mengatur suara saat bekerja kelompok',
    'Permainan kepercayaan (trust game sederhana)',
    'Menulis harapan baik untuk teman',
    'Latihan fokus (mindfulness sederhana 1–2 menit)',
    'Menjaga barang pribadi tetap rapi',
    'Mengembalikan buku ke tempatnya',
    'Menjadi pendengar aktif (eye contact, angguk)',
    'Menyebut nama teman dengan benar (menghargai identitas)',
    'Membuat proyek kecil untuk membantu sekolah',
    'Mengunjungi perpustakaan dan menjaga ketertiban',
    'Latihan sabar saat menunggu giliran permainan',
    'Menghargai waktu istirahat orang lain',
    'Tidak memotong antrean di kantin',
    'Menghargai karya teman (tidak merusak)',
    'Membuat jadwal belajar di rumah',
    'Berlatih meminta bantuan dengan sopan',
    'Menawarkan bantuan tanpa diminta',
    'Menghindari kata-kata kasar',
    'Mengganti kata negatif jadi positif',
    'Latihan mengendalikan emosi (tarik napas)',
    'Membuat daftar aturan keselamatan kelas',
    'Simulasi evakuasi sederhana',
    'Menjaga kebersihan meja sendiri',
    'Menghapus papan tulis setelah dipakai',
    'Mengapresiasi usaha, bukan hanya hasil',
    'Membuat target kebaikan mingguan',
    'Mengingatkan teman dengan cara baik',
    'Menghargai perbedaan pendapat',
    'Tidak menertawakan kesalahan teman',
    'Latihan meminta maaf dengan tulus (lebih mendalam)',
    'Memberi kesempatan teman berbicara',
    'Tidak menyebarkan gosip',
    'Mengucapkan selamat ulang tahun sederhana',
    'Membuat jadwal “hari tanpa mengeluh”',
    'Menghargai guru dan staf sekolah',
    'Menjaga ketertiban saat upacara',
    'Membantu teman yang tertinggal pelajaran',
    'Membuat proyek kebersihan lingkungan sekitar',
    'Menyiram tanaman sekolah',
    'Menjaga fasilitas umum (toilet, taman)',
    'Tidak membuang sampah sembarangan',
    'Menggunakan bahasa yang sopan',
    'Menyusun tas sendiri dengan rapi',
    'Datang tepat waktu ke kelas',
    'Menghargai waktu belajar',
    'Mengurangi kebisingan saat guru menjelaskan',
    'Menjaga antrian saat keluar kelas',
    'Menjadi contoh bagi adik kelas',
    'Membuat drama kecil tentang kejujuran',
    'Membuat lagu sederhana tentang kebaikan',
    'Menggambar situasi tolong-menolong',
    'Membaca nyaring untuk teman',
    'Menjaga rahasia teman (yang aman)',
    'Menghormati privasi orang lain',
    'Menghindari mengambil hak orang lain',
    'Mengucapkan doa sebelum/akhir kegiatan',
    'Menghargai budaya dan kebiasaan berbeda',
    'Menyusun rencana kegiatan kelas bersama',
    'Evaluasi mingguan: apa kebaikan yang sudah dilakukan',
    'Salam pagi di pintu kelas (senyum & sapa)',
    '“Check-in emosi” dengan kartu perasaan',
    'Berbagi cerita kebaikan hari ini',
    'Menulis surat terima kasih untuk petugas sekolah',
    'Membuat kartu ucapan untuk teman yang sakit',
    'Hari tanpa mengejek (anti-bullying day)',
    'Tukar tempat duduk untuk mengenal teman baru',
    'Mendengarkan cerita teman tanpa menyela',
    'Permainan “tebak perasaan” dari ekspresi',
    'Latihan memberi pujian yang tulus',
    'Membuat poster kata-kata baik',
    'Membaca buku tentang empati lalu diskusi',
    'Menjaga tanaman kelas bersama',
    'Menghemat air saat cuci tangan',
    'Mematikan lampu/AC saat tidak dipakai',
    'Bank sampah mini di kelas',
    'Membuat kerajinan dari barang bekas',
    'Hari bawa bekal sehat dan berbagi cerita',
    'Olahraga bersama dengan aturan fair play',
    'Menyusun aturan kelas bersama',
    'Menjadi “penjaga ketenangan” bergiliran',
    'Latihan meminta izin sebelum meminjam',
    'Menyusun jadwal tugas pribadi',
    'Membantu guru membagikan buku',
    'Menjadi “penyemangat” untuk teman yang gugup',
    'Membuat komitmen kelas (janji bersama)',
    'Menonton video pendek tentang kebaikan lalu refleksi',
    'Menulis daftar hal yang disyukuri',
    'Permainan kerja sama (misalnya estafet tim)',
    'Latihan menerima kekalahan dengan sportif',
    'Mengucapkan selamat kepada pemenang',
    'Membuat sudut baca nyaman untuk semua',
    'Bergiliran menjadi pemimpin doa',
    'Membantu merapikan alat belajar bersama',
    'Latihan berbicara jujur dalam situasi sulit',
    'Menghargai perbedaan (diskusi sederhana)',
    'Membuat “pohon kebaikan” di dinding kelas',
    'Mengumpulkan cerita inspiratif dari rumah',
    'Latihan menyapa orang dengan sopan',
    'Simulasi menolong orang yang membutuhkan',
    'Membuat aturan penggunaan gadget (jika ada)',
    'Mengatur suara saat bekerja kelompok',
    'Permainan kepercayaan (trust game sederhana)',
    'Menulis harapan baik untuk teman',
    'Latihan fokus (mindfulness sederhana 1–2 menit)',
    'Menjaga barang pribadi tetap rapi',
    'Mengembalikan buku ke tempatnya',
    'Menjadi pendengar aktif (eye contact, angguk)',
    'Menyebut nama teman dengan benar (menghargai identitas)',
    'Membuat proyek kecil untuk membantu sekolah',
    'Mengunjungi perpustakaan dan menjaga ketertiban',
    'Latihan sabar saat menunggu giliran permainan',
    'Menghargai waktu istirahat orang lain',
    'Tidak memotong antrean di kantin',
    'Menghargai karya teman (tidak merusak)',
    'Membuat jadwal belajar di rumah',
    'Berlatih meminta bantuan dengan sopan',
    'Menawarkan bantuan tanpa diminta',
    'Menghindari kata-kata kasar',
    'Mengganti kata negatif jadi positif',
    'Latihan mengendalikan emosi (tarik napas)',
    'Membuat daftar aturan keselamatan kelas',
    'Simulasi evakuasi sederhana',
    'Menjaga kebersihan meja sendiri',
    'Menghapus papan tulis setelah dipakai',
    'Mengapresiasi usaha, bukan hanya hasil',
    'Membuat target kebaikan mingguan',
    'Mengingatkan teman dengan cara baik',
    'Menghargai perbedaan pendapat',
    'Tidak menertawakan kesalahan teman',
    'Latihan meminta maaf dengan tulus (lebih mendalam)',
    'Memberi kesempatan teman berbicara',
    'Tidak menyebarkan gosip',
    'Mengucapkan selamat ulang tahun sederhana',
    'Membuat jadwal “hari tanpa mengeluh”',
    'Menghargai guru dan staf sekolah',
    'Menjaga ketertiban saat upacara',
    'Membantu teman yang tertinggal pelajaran',
    'Membuat proyek kebersihan lingkungan sekitar',
    'Menyiram tanaman sekolah',
    'Menjaga fasilitas umum (toilet, taman)',
    'Tidak membuang sampah sembarangan',
    'Menggunakan bahasa yang sopan',
    'Menyusun tas sendiri dengan rapi',
    'Datang tepat waktu ke kelas',
    'Menghargai waktu belajar',
    'Mengurangi kebisingan saat guru menjelaskan',
    'Menjaga antrian saat keluar kelas',
    'Menjadi contoh bagi adik kelas',
    'Membuat drama kecil tentang kejujuran',
    'Membuat lagu sederhana tentang kebaikan',
    'Menggambar situasi tolong-menolong',
    'Membaca nyaring untuk teman',
    'Menjaga rahasia teman (yang aman)',
    'Menghormati privasi orang lain',
    'Menghindari mengambil hak orang lain',
    'Mengucapkan doa sebelum/akhir kegiatan',
    'Menghargai budaya dan kebiasaan berbeda',
    'Menyusun rencana kegiatan kelas bersama',
    'Evaluasi mingguan: apa kebaikan yang sudah dilakukan',
    'Menulis “janji hari ini” di awal pelajaran',
    'Membuat simbol kelas (logo kebersamaan)',
    'Permainan saling mengenal lebih dalam',
    'Membuat daftar kebiasaan baik di rumah',
    'Berlatih menyebut kelebihan diri sendiri',
    'Menulis kelebihan teman sebangku',
    'Latihan mendengar instruksi tanpa diulang',
    'Bermain peran menjadi guru (menghargai peran)',
    'Membuat aturan berbicara sopan di grup kelas',
    'Simulasi meminjam barang dengan izin',
    'Mengucapkan salam saat masuk ruangan mana pun',
    'Menyusun target kebaikan pribadi',
    'Menghargai antrean saat naik kendaraan sekolah',
    'Latihan berbicara pelan di dalam ruangan',
    'Mengucapkan “silakan duluan”',
    'Memberi tempat duduk kepada yang membutuhkan',
    'Latihan berjalan tertib di lorong sekolah',
    'Membuat jadwal tidur sehat',
    'Membuat komitmen tidak berbohong sehari penuh',
    'Permainan “kata baik berantai”',
    'Menulis cerita tentang kejujuran',
    'Diskusi akibat dari berbuat curang',
    'Bermain game yang menuntut kerja sama total',
    'Membuat papan “kata hari ini” (kata positif)',
    'Menyusun aturan saat bermain bersama',
    'Latihan tidak menyela percakapan orang lain',
    'Menulis pengalaman menolong orang',
    'Membuat daftar hal yang membuat marah & solusinya',
    'Simulasi meminta maaf setelah berbuat salah',
    'Membuat kartu motivasi untuk diri sendiri',
    'Mengingat nama semua teman sekelas',
    'Latihan menyapa dengan kontak mata',
    'Membiasakan mengetuk pintu sebelum masuk',
    'Latihan duduk rapi saat belajar',
    'Menghargai hasil karya tanpa membandingkan',
    'Mengumpulkan cerita teladan dari orang tua',
    'Membuat “hari sopan santun”',
    'Permainan peran tentang berbagi mainan',
    'Membuat daftar ucapan sopan selain “tolong”',
    'Latihan memberi instruksi dengan jelas',
    'Bermain tebak solusi masalah sederhana',
    'Membuat komitmen tidak mengejek fisik',
    'Diskusi tentang arti tanggung jawab',
    'Latihan mengembalikan barang tepat waktu',
    'Membuat jadwal piket pribadi di rumah',
    'Simulasi menolak ajakan buruk dengan sopan',
    'Membuat cerita bergambar tentang empati',
    'Latihan menjaga rahasia teman',
    'Menulis surat permintaan maaf',
    'Permainan menghargai giliran berbicara',
    'Mengingatkan teman secara baik',
    'Latihan bersabar saat kalah permainan',
    'Membuat daftar kebiasaan buruk yang ingin diubah',
    'Diskusi tentang pentingnya menepati janji',
    'Latihan memberi salam ke guru lain',
    'Membuat kegiatan “diam sejenak” (self-control)',
    'Latihan tidak memotong pembicaraan',
    'Membuat jurnal kebaikan mingguan',
    'Permainan mengenali emosi teman',
    'Diskusi tentang keadilan',
    'Membuat aturan bermain adil',
    'Latihan tidak iri pada keberhasilan teman',
    'Menyusun tujuan belajar pribadi',
    'Latihan menerima kritik dengan baik',
    'Membuat daftar kata kasar yang harus dihindari',
    'Mengubah kata kasar jadi kata sopan',
    'Simulasi situasi kehilangan barang',
    'Latihan bertanggung jawab atas kesalahan',
    'Membuat poster kejujuran',
    'Diskusi akibat membuang waktu',
    'Latihan fokus tanpa gangguan',
    'Membuat aturan saat meminjam alat tulis',
    'Bermain peran sebagai penolong',
    'Menyusun rencana membantu orang tua',
    'Latihan menyelesaikan tugas sampai tuntas',
    'Membuat daftar kebiasaan hemat',
    'Diskusi pentingnya menjaga kesehatan',
    'Latihan mencuci tangan dengan benar',
    'Membuat aturan makan bersama',
    'Latihan berbagi makanan dengan adil',
    'Membuat jadwal minum air',
    'Latihan menjaga kebersihan diri',
    'Diskusi menghargai perbedaan agama',
    'Membuat aturan toleransi sederhana',
    'Latihan menghormati teman yang berdoa',
    'Diskusi tentang saling menghargai',
    'Membuat cerita tentang persahabatan',
    'Latihan tidak pilih-pilih teman',
    'Permainan kerja sama lintas kelompok',
    'Membuat kelompok acak tiap minggu',
    'Latihan menerima anggota kelompok baru',
    'Diskusi tentang kepercayaan',
    'Membuat kontrak kepercayaan',
    'Latihan tidak berbohong walau sulit',
    'Membuat simulasi kejujuran saat ujian',
    'Diskusi dampak menyontek',
    'Latihan berkata “saya belum tahu”',
    'Membuat budaya bertanya tanpa takut',
    'Latihan menghargai pertanyaan teman',
    'Diskusi tentang rasa malu & percaya diri',
    'Latihan berbicara di depan kelompok kecil',
    'Membuat daftar keberanian kecil',
    'Simulasi meminta bantuan guru',
    'Latihan tidak takut mencoba',
    'Membuat jurnal “aku berani hari ini”',
    'Diskusi tentang kegagalan',
    'Latihan bangkit setelah gagal',
    'Membuat cerita kegagalan jadi pelajaran',
    'Latihan tidak menyalahkan orang lain',
    'Diskusi tanggung jawab pribadi',
    'Membuat target mingguan realistis',
    'Latihan konsisten menjalankan kebiasaan',
    'Membuat checklist harian',
    'Latihan mengevaluasi diri',
    'Diskusi pentingnya usaha',
    'Membuat grafik usaha vs hasil',
    'Latihan tidak menyerah',
    'Diskusi tentang kesabaran',
    'Latihan menunggu tanpa mengeluh',
    'Membuat kegiatan “hari tanpa marah”',
    'Latihan mengontrol emosi saat kalah',
    'Diskusi penyebab konflik',
    'Simulasi menyelesaikan konflik damai',
    'Membuat aturan tidak membalas ejekan',
    'Latihan memaafkan teman',
    'Diskusi arti memaafkan',
    'Membuat daftar hal yang bisa dimaafkan',
    'Latihan berbicara dengan nada lembut',
    'Diskusi pentingnya nada bicara',
    'Membuat permainan komunikasi jelas',
    'Latihan menyampaikan pesan tanpa salah paham',
    'Diskusi pentingnya mendengar',
    'Membuat permainan mendengar instruksi',
    'Latihan fokus saat orang lain bicara',
    'Diskusi arti menghargai waktu orang lain',
    'Latihan datang sebelum waktu',
    'Membuat aturan tidak terlambat',
    'Diskusi dampak keterlambatan',
    'Latihan menghargai jadwal',
    'Membuat simulasi manajemen waktu',
    'Diskusi tentang prioritas',
    'Latihan memilih kegiatan penting',
    'Membuat daftar tugas harian',
    'Latihan menyelesaikan tugas tepat waktu',
    'Diskusi tanggung jawab sekolah & rumah',
    'Membuat perbandingan tugas rumah vs sekolah',
    'Latihan tidak menunda pekerjaan',
    'Diskusi tentang kebiasaan buruk menunda',
    'Membuat strategi menghindari malas',
    'Latihan disiplin tanpa diingatkan',
    'Diskusi pentingnya kejujuran kecil',
    'Latihan tidak mengambil barang temuan',
    'Membuat simulasi menemukan uang',
    'Diskusi tentang amanah',
    'Latihan menjaga titipan',
    'Membuat kegiatan titip-menitip barang',
    'Diskusi pentingnya kepercayaan teman',
    'Latihan menjaga janji sederhana',
    'Membuat kontrak janji pribadi',
    'Diskusi tentang integritas',
    'Latihan konsisten antara kata & tindakan',
    'Membuat cerita tentang orang jujur',
    'Diskusi tentang teladan',
    'Meniru perilaku tokoh baik',
    'Latihan menjadi contoh bagi teman',
    'Diskusi pengaruh teman sebaya',
    'Latihan memilih teman yang baik',
    'Membuat daftar ciri teman baik',
    'Diskusi dampak pergaulan',
    'Latihan berkata “tidak” pada hal buruk',
    'Membuat simulasi tekanan teman',
    'Diskusi keberanian moral',
    'Latihan membela yang benar',
    'Membuat cerita tentang keberanian',
    'Diskusi arti kepemimpinan',
    'Latihan memimpin kelompok kecil',
    'Membuat rotasi pemimpin harian',
    'Diskusi tanggung jawab pemimpin',
    'Latihan mendengarkan anggota',
    'Membuat evaluasi kepemimpinan',
    'Diskusi kerja sama tim',
    'Latihan berbagi tugas adil',
    'Membuat refleksi kerja tim',
    'Diskusi konflik dalam tim',
    'Latihan menyelesaikan konflik kelompok',
    'Membuat aturan tim yang sehat',
    'Diskusi pentingnya komunikasi',
    'Latihan komunikasi dua arah',
    'Membuat simulasi miskomunikasi',
    'Diskusi solusi komunikasi',
    'Latihan berbicara jujur tapi sopan',
    'Membuat latihan empati lanjutan',
    'Diskusi memahami perasaan orang lain',
    'Latihan membayangkan posisi orang lain',
    'Membuat kegiatan “hari peduli”',
    'Diskusi tentang membantu tanpa diminta',
    'Latihan spontan menolong',
    'Membuat proyek kecil kebaikan kelas',
    'Diskusi dampak kebaikan kecil',
    'Refleksi akhir: perubahan diri yang dirasakan'
];
//get random activity
const randomIndex = Math.floor(Math.random() * activities.length);
const randomActivity = activities[randomIndex];
//menampilkan ke html kebiasaan baik secara random tiap dua detik
const activityElement = document.getElementById('kebiasaanBaik');
setInterval(() => {
    const randomIndex = Math.floor(Math.random() * activities.length);
    const randomActivity = activities[randomIndex];
    activityElement.textContent = randomActivity;
}, 2000);