const baseIdeas = [
    "penjumlahan benda sehari-hari",
    "pengurangan dengan cerita sederhana",
    "perkalian sebagai penjumlahan berulang",
    "pembagian dengan membagi kue",
    "mengenal angka lewat kartu",
    "urutkan angka kecil ke besar",
    "urutkan angka besar ke kecil",
    "membandingkan dua angka",
    "tanda lebih besar dan lebih kecil",
    "mengenal angka ganjil genap",
    "mencari pola angka sederhana",
    "melanjutkan pola gambar",
    "mengenal bangun datar",
    "mencari bentuk di kelas",
    "menghitung benda di kelas",
    "tebak angka",
    "garis bilangan di lantai",
    "lompat angka",
    "permainan dadu berhitung",
    "berhitung dengan jari",
    "berhitung dengan batu/kancing",
    "soal cerita belanja",
    "simulasi toko kecil",
    "menghitung uang mainan",
    "menghitung kembalian",
    "pengukuran panjang benda",
    "pengukuran dengan jengkal",
    "pengukuran berat sederhana",
    "menimbang benda kelas",
    "membaca jam analog",
    "menghitung waktu kegiatan",
    "permainan “lebih banyak atau sedikit”",
    "puzzle angka",
    "menyusun angka acak",
    "mencari pasangan angka",
    "bingo angka",
    "matematika dengan Lego",
    "membuat pola dengan balok",
    "menghitung sisi bangun datar",
    "mengenal keliling",
    "mengenal luas",
    "menghitung luas dengan kotak-kotak",
    "menghitung keliling dengan tali",
    "membagi pizza gambar",
    "membagi kue gambar",
    "soal cerita sederhana",
    "cerita matematika harian",
    "tantangan hitung cepat",
    "lomba berhitung kelompok",
    "permainan kartu matematika",
    "matematika dengan lagu",
    "menghitung skor permainan",
    "lempar bola dan hitung",
    "loncat tali sambil berhitung",
    "jalan sambil berhitung langkah",
    "menghitung benda warna tertentu",
    "klasifikasi benda berdasarkan bentuk",
    "klasifikasi berdasarkan ukuran",
    "klasifikasi berdasarkan warna",
    "membuat grafik sederhana",
    "membaca grafik gambar",
    "membuat diagram batang sederhana",
    "mengenal pecahan dari makanan",
    "membagi roti jadi bagian sama",
    "membagi apel jadi bagian sama",
    "mengenal setengah dan seperempat",
    "mengenal setengah jam",
    "membaca jam setengah",
    "menghitung hari dalam seminggu",
    "menghitung bulan dalam setahun",
    "kalender sederhana",
    "urutan tanggal",
    "menebak hasil penjumlahan",
    "menebak hasil pengurangan",
    "permainan “benar atau salah” angka",
    "mencari angka hilang",
    "isi pola angka kosong",
    "operasi campuran sederhana",
    "berhitung dengan kartu remi",
    "membuat soal sendiri",
    "tukar soal dengan teman",
    "koreksi soal teman",
    "belajar dari kesalahan hitung",
    "hitung cepat mental math",
    "strategi perkalian sederhana",
    "tabel perkalian dasar",
    "permainan tabel perkalian",
    "mencari kelipatan sederhana",
    "mengenal faktor sederhana",
    "membagi kelompok sama rata",
    "simulasi berbagi makanan",
    "menghitung jumlah langkah ke sekolah",
    "estimasi jumlah benda",
    "cek hasil estimasi",
    "permainan “perkiraan paling dekat”",
    "matematika dengan gambar hewan",
    "matematika dengan buah-buahan",
    "matematika dengan mainan",
    "matematika dengan aktivitas olahraga",
    "menghitung volume benda sederhana",
    "tantangan logika sederhana",
    "teka-teki angka sederhana",
    "proyek mini “matematika di sekitar kita”",
    "mengenal bagian tumbuhan",
    "fungsi akar, batang, daun",
    "siklus hidup kupu-kupu",
    "siklus hidup katak",
    "mengenal hewan herbivora",
    "mengenal hewan karnivora",
    "mengenal hewan omnivora",
    "klasifikasi hewan sederhana",
    "habitat hewan",
    "rantai makanan sederhana",
    "sumber energi makanan",
    "makanan sehat dan tidak sehat",
    "pencernaan manusia sederhana",
    "pernapasan manusia",
    "fungsi organ tubuh dasar",
    "menjaga kesehatan tubuh",
    "kebersihan diri",
    "pentingnya air bersih",
    "perubahan wujud benda",
    "padat cair gas",
    "penguapan air",
    "pembekuan air",
    "mencairnya es",
    "siklus air",
    "hujan dan prosesnya",
    "cuaca harian",
    "musim dan perubahan alam",
    "pengamatan awan",
    "pengamatan angin",
    "pengamatan hujan",
    "gaya dorong dan tarik",
    "magnet sederhana",
    "benda yang bisa ditarik magnet",
    "listrik sederhana",
    "rangkaian listrik sederhana",
    "sumber energi listrik",
    "energi matahari",
    "energi angin",
    "energi air",
    "perubahan energi",
    "bunyi dan getaran",
    "sumber bunyi",
    "cahaya dan bayangan",
    "sifat cahaya",
    "cermin sederhana",
    "pembiasan cahaya sederhana",
    "bumi dan tata surya",
    "matahari sebagai sumber energi",
    "gerak benda",
    "gaya gravitasi",
    "benda menggelinding",
    "benda jatuh",
    "benda melayang",
    "klasifikasi benda di sekitar",
    "sifat benda padat",
    "sifat benda cair",
    "sifat benda gas",
    "perubahan lingkungan",
    "menjaga lingkungan",
    "daur ulang sederhana",
    "sampah organik dan anorganik",
    "kompos sederhana",
    "tanaman dan pertumbuhan",
    "kebutuhan tumbuhan",
    "fotosintesis sederhana",
    "bagian bunga",
    "penyerbukan sederhana",
    "perkembangbiakan hewan",
    "perkembangbiakan tumbuhan",
    "benih dan perkecambahan",
    "struktur tanah",
    "jenis tanah sederhana",
    "batuan dan jenisnya",
    "erosi sederhana",
    "gunung dan pegunungan",
    "sungai dan danau",
    "laut dan kehidupan laut",
    "ekosistem sederhana",
    "hubungan makhluk hidup",
    "adaptasi hewan",
    "adaptasi tumbuhan",
    "perubahan musim dan hewan",
    "alat indera manusia",
    "fungsi mata",
    "fungsi telinga",
    "fungsi hidung",
    "fungsi lidah",
    "fungsi kulit",
    "menjaga kesehatan indera",
    "kebiasaan hidup sehat",
    "olahraga dan tubuh",
    "detak jantung sederhana",
    "pernapasan saat olahraga",
    "energi dalam tubuh",
    "makanan sebagai energi",
    "eksperimen air sederhana",
    "eksperimen udara sederhana",
    "eksperimen cahaya sederhana",
    "eksperimen magnet sederhana",
    "proyek sains sederhana di sekitar rumah/sekolah",
    "membaca cerita pendek",
    "menceritakan kembali isi bacaan",
    "menemukan tokoh utama cerita",
    "menemukan pesan moral cerita",
    "membuat ringkasan bacaan",
    "membaca nyaring di depan kelas",
    "membaca dalam hati",
    "membaca bergantian berpasangan",
    "membaca bersama kelompok",
    "membaca buku cerita anak",
    "membaca komik edukatif",
    "membaca dongeng tradisional",
    "membaca legenda daerah",
    "membaca fabel",
    "membaca cerita rakyat",
    "mengenali ide pokok paragraf",
    "mencari kalimat utama",
    "membuat judul dari cerita",
    "menebak isi cerita dari judul",
    "menulis ulang cerita sederhana",
    "menulis akhir cerita berbeda",
    "menulis awal cerita berbeda",
    "menulis karakter cerita",
    "menggambar isi cerita",
    "membuat peta cerita",
    "membuat alur cerita sederhana",
    "mengenal jenis-jenis teks",
    "teks deskripsi sederhana",
    "teks narasi sederhana",
    "teks prosedur sederhana",
    "menulis petunjuk sederhana",
    "membaca instruksi dan mengikuti",
    "membuat cerita dari gambar",
    "menyusun gambar menjadi cerita",
    "menulis jurnal harian",
    "menulis pengalaman pribadi",
    "menulis kegiatan sehari-hari",
    "membaca puisi anak",
    "menulis puisi sederhana",
    "membaca pantun",
    "membuat pantun sederhana",
    "membaca dialog sederhana",
    "membuat percakapan",
    "bermain peran dari teks",
    "membaca berita sederhana",
    "menulis berita kelas",
    "membuat poster literasi",
    "membuat slogan membaca",
    "membaca label dan informasi",
    "memahami teks instruksi",
    "mencari kata sulit",
    "mencari arti kata baru",
    "membuat kamus kecil",
    "menulis kosakata baru",
    "permainan kata",
    "menyusun kata acak",
    "menyusun kalimat acak",
    "melengkapi kalimat rumpang",
    "menemukan sinonim sederhana",
    "menemukan antonim sederhana",
    "membaca cerita berantai",
    "melanjutkan cerita teman",
    "membaca buku favorit",
    "merekomendasikan buku",
    "membuat resensi buku sederhana",
    "menggambar sampul buku",
    "membuat karakter cerita sendiri",
    "membuat cerita fantasi sederhana",
    "membuat cerita sehari-hari",
    "membaca teks informasi sederhana",
    "memahami isi bacaan sains sederhana",
    "membaca teks budaya",
    "membaca teks lingkungan",
    "diskusi isi bacaan",
    "menjawab pertanyaan bacaan",
    "membuat pertanyaan dari teks",
    "permainan “siapa cepat memahami”",
    "membaca dengan ekspresi",
    "membaca dengan intonasi",
    "membaca peran dalam drama",
    "membuat drama sederhana",
    "menulis naskah pendek",
    "membaca cerita bergambar",
    "membuat cerita bergambar sendiri",
    "membaca teks digital sederhana",
    "literasi media sederhana",
    "memahami informasi dari poster",
    "memahami infografik sederhana",
    "membaca tabel sederhana",
    "membaca grafik sederhana",
    "membuat catatan bacaan",
    "membuat mind map bacaan",
    "meringkas buku cerita",
    "membaca cerita berlevel",
    "tantangan membaca harian",
    "membaca dalam waktu tertentu",
    "lomba membaca",
    "klub membaca kelas",
    "berbagi cerita di kelas",
    "proyek literasi “satu buku satu cerita”",
];

const twists = [
    "siswa mengajar guru selama 5 menit",
    "semua soal berubah setelah dibaca",
    "pelajaran dimulai dari akhir materi",
    "guru sengaja “lupa” bagian penting agar siswa mencari",
    "tugas hanya bisa diselesaikan sambil berjalan",
    "kelas hanya boleh berbisik, tidak boleh bicara normal",
    "semua penilaian berbasis cerita, bukan angka",
    "setiap siswa mendapat materi berbeda",
    "belajar dimulai dari pertanyaan, bukan materi",
    "siswa membuat aturan belajar sendiri",
    "guru berubah peran jadi “penasihat misterius”",
    "semua kesalahan dianggap “petunjuk emas”",
    "tugas berubah setiap 3 menit",
    "satu pelajaran disamarkan sebagai permainan",
    "siswa harus menjelaskan tanpa menggunakan kata tertentu",
    "semua jawaban harus dalam bentuk gambar",
    "pelajaran hanya bisa dipahami jika dijelaskan ulang teman",
    "materi disampaikan seperti teka-teki",
    "kelas dimulai tanpa penjelasan tujuan",
    "siswa memilih sendiri cara belajar hari itu",
    "setiap siswa jadi “ahli” topik berbeda",
    "guru hanya boleh memberi pertanyaan",
    "semua penjelasan harus berasal dari siswa",
    "jawaban harus dibuktikan dengan contoh nyata",
    "tidak boleh menggunakan buku sampai akhir pelajaran",
    "semua materi disampaikan acak",
    "siswa harus mengajarkan kembali materi sebelum paham",
    "setiap kesalahan membuka level baru",
    "pelajaran dimulai dengan simulasi nyata",
    "semua instruksi disembunyikan dalam cerita",
    "siswa harus belajar dari kesalahan teman",
    "tugas hanya bisa selesai jika kerja sama penuh",
    "kelas tanpa kursi (harus bergerak)",
    "semua jawaban harus disampaikan sebagai drama",
    "materi berubah tergantung suara kelas",
    "setiap siswa mendapat “misi rahasia”",
    "guru sengaja memberi petunjuk tidak lengkap",
    "tidak ada jawaban final, hanya revisi",
    "siswa harus menemukan “aturan tersembunyi”",
    "pelajaran dimulai dari eksperimen gagal",
    "semua konsep diajarkan lewat permainan peran",
    "siswa harus menjelaskan sebelum diberi materi",
    "setiap pelajaran punya “twist kejutan”",
    "jawaban terbaik adalah yang paling kreatif, bukan benar",
    "semua tugas harus dikerjakan berpasangan acak",
    "siswa menilai diri sendiri sebelum guru",
    "materi hanya muncul setelah diskusi",
    "kelas berubah jadi simulasi dunia nyata",
    "semua soal punya lebih dari satu jawaban benar",
    "guru pura-pura salah untuk memancing diskusi",
    "siswa harus membantah materi untuk memahami",
    "semua konsep diajarkan melalui cerita absurd",
    "pelajaran dimulai dengan “kesalahan besar”",
    "siswa harus menemukan apa yang hilang",
    "setiap pelajaran disamarkan sebagai misteri",
    "jawaban harus ditemukan lewat gerakan",
    "tidak boleh menulis selama 10 menit pertama",
    "semua penjelasan harus dibuat ulang siswa",
    "pelajaran berubah sesuai keputusan kelas",
    "siswa harus membuat soal sendiri sebelum belajar",
    "semua tugas harus diselesaikan tanpa kata kunci tertentu",
    "guru hanya boleh menggunakan gambar",
    "semua konsep diajarkan lewat analogi aneh",
    "kelas dimulai dengan kebingungan terkontrol",
    "siswa harus belajar tanpa mengetahui topik awal",
    "setiap materi punya “mode rahasia”",
    "jawaban harus disampaikan seperti puisi",
    "pelajaran hanya aktif jika semua siswa diam",
    "setiap siswa memegang bagian informasi berbeda",
    "materi disampaikan dalam potongan acak",
    "siswa harus menyusun ulang pelajaran",
    "tidak boleh ada catatan sampai akhir",
    "semua diskusi harus dalam bentuk pertanyaan",
    "guru memberi jawaban tapi salah satu selalu palsu",
    "siswa harus menebak mana yang benar",
    "pelajaran berubah menjadi permainan detektif",
    "semua konsep diajarkan lewat simulasi hidup",
    "siswa harus menyelesaikan misi tanpa tahu tujuannya",
    "setiap jawaban membuka petunjuk baru",
    "kelas dimulai dari kesimpulan dulu",
    "siswa harus membuat kesimpulan sendiri",
    "semua materi disamarkan sebagai cerita misteri",
    "jawaban harus disetujui oleh teman",
    "pelajaran hanya selesai jika semua setuju",
    "guru berubah jadi “game master”",
    "siswa harus mencari “bug” dalam materi",
    "semua pelajaran berbentuk tantangan",
    "setiap konsep diajarkan lewat kesalahan umum",
    "siswa harus memperbaiki materi guru",
    "semua jawaban harus dipresentasikan sebagai komedi",
    "pelajaran dimulai dari hal paling aneh",
    "siswa harus mengubah materi jadi cerita",
    "semua tugas berbasis eksplorasi bebas",
    "jawaban harus ditemukan tanpa instruksi",
    "setiap pelajaran punya “aturan tersembunyi”",
    "siswa harus menebak aturan itu",
    "semua materi hanya berupa petunjuk",
    "pelajaran berakhir dengan pertanyaan, bukan jawaban"
];

const teknik = [
    "tanya jawab cepat",
    "diskusi berpasangan",
    "diskusi kelompok kecil",
    "diskusi kelas",
    "presentasi siswa",
    "ceramah singkat",
    "demonstrasi langsung",
    "praktik langsung",
    "eksperimen sederhana",
    "simulasi",
    "role play",
    "permainan edukatif",
    "kuis cepat",
    "brainstorming ide",
    "mind mapping",
    "membuat catatan ringkas",
    "membuat rangkuman",
    "membaca nyaring",
    "membaca dalam hati",
    "membaca berantai",
    "jigsaw learning",
    "think pair share",
    "gallery walk",
    "station learning",
    "rotating group",
    "peer teaching",
    "tutor sebaya",
    "belajar mandiri",
    "proyek kelompok",
    "proyek individu",
    "studi kasus",
    "pemecahan masalah",
    "inquiry sederhana",
    "discovery learning",
    "pembelajaran berbasis proyek",
    "pembelajaran berbasis masalah",
    "pembelajaran kontekstual",
    "pembelajaran berbasis pengalaman",
    "flipped classroom",
    "blended learning",
    "hybrid learning",
    "micro teaching",
    "latihan soal bertahap",
    "drill and practice",
    "permainan kartu edukatif",
    "permainan papan edukatif",
    "storytelling",
    "menulis kreatif",
    "jurnal harian",
    "refleksi diri",
    "peer review",
    "self assessment",
    "observasi langsung",
    "pengamatan lapangan",
    "eksperimen kelompok",
    "demonstrasi guru",
    "modeling",
    "scaffolding",
    "guided practice",
    "independent practice",
    "latihan berulang",
    "retrieval practice",
    "spaced repetition",
    "chunking materi",
    "analogi sederhana",
    "visualisasi konsep",
    "penggunaan gambar",
    "penggunaan video",
    "penggunaan audio",
    "pembelajaran multisensori",
    "diskusi debat",
    "debat terstruktur",
    "presentasi poster",
    "membuat infografik",
    "membuat diagram",
    "membuat tabel",
    "simulasi peran sosial",
    "proyek sosial",
    "pembelajaran layanan masyarakat",
    "kunjungan lapangan",
    "outdoor learning",
    "learning by doing",
    "eksperimen rumah",
    "latihan berbasis tantangan",
    "problem solving cepat",
    "permainan logika",
    "puzzle edukatif",
    "quiz kompetitif",
    "pembelajaran kolaboratif",
    "pembelajaran kooperatif",
    "diskusi reflektif",
    "diskusi terbuka",
    "pertanyaan pemantik",
    "inquiry berbasis pertanyaan",
    "eksplorasi mandiri",
    "pembelajaran bertahap",
    "pengulangan terarah",
    "evaluasi formatif",
    "evaluasi sumatif",
    "pembelajaran adaptif berbasis kebutuhan siswa"
];

const constraints = [
    "harus mendorong rasa ingin tahu siswa",
    "harus meningkatkan pemahaman, bukan hafalan",
    "harus memberikan ruang untuk mencoba dan merasa aman menghadapi kegagalan",
    "harus mendukung gaya belajar yang berbeda",
    "harus memungkinkan siswa belajar dengan ritme sendiri",
    "harus memperkuat kolaborasi antar siswa",
    "harus mendorong komunikasi yang sehat",
    "harus meningkatkan kepercayaan diri siswa",
    "harus memberikan umpan balik yang membangun",
    "harus fokus pada proses belajar",
    "harus menghargai usaha siswa",
    "harus mengurangi tekanan akademik berlebihan",
    "harus membuat siswa merasa aman bertanya",
    "harus mendorong kreativitas",
    "harus menghubungkan materi dengan kehidupan nyata",
    "harus meningkatkan keterlibatan siswa",
    "harus mendukung pembelajaran aktif",
    "harus memberi ruang refleksi diri",
    "harus mendorong pemikiran kritis",
    "harus memperkuat problem solving",
    "harus fleksibel terhadap kemampuan siswa",
    "harus inklusif untuk semua siswa",
    "harus mudah dipahami",
    "harus menyenangkan untuk dijalani",
    "harus meningkatkan motivasi intrinsik",
    "harus mendukung pembelajaran mandiri",
    "harus tetap terstruktur namun tidak kaku",
    "harus memberi ruang eksplorasi",
    "harus memperkuat kerja sama tim",
    "harus mengajarkan tanggung jawab",
    "harus mendorong rasa percaya diri",
    "harus membantu siswa menemukan minatnya",
    "harus meningkatkan fokus belajar",
    "harus mengurangi distraksi negatif",
    "harus mendukung pembelajaran bertahap",
    "harus memungkinkan diferensiasi tugas",
    "harus mendukung pembelajaran berbasis proyek",
    "harus meningkatkan keterampilan komunikasi",
    "harus memperkuat empati antar siswa",
    "harus mendukung pembelajaran kontekstual",
    "harus meningkatkan pemahaman jangka panjang",
    "harus mendukung evaluasi diri",
    "harus memberikan feedback cepat dan jelas",
    "harus mendukung pembelajaran kolaboratif",
    "harus mendorong diskusi sehat",
    "harus meningkatkan keterlibatan aktif",
    "harus mendukung eksplorasi ide",
    "harus menghubungkan teori dan praktik",
    "harus memperkuat literasi dasar",
    "harus meningkatkan numerasi dasar",
    "harus mendorong rasa tanggung jawab belajar",
    "harus mendukung pembelajaran berbasis pengalaman",
    "harus fleksibel dalam metode",
    "harus tetap menjaga tujuan pembelajaran",
    "harus memperkuat kemampuan analitis",
    "harus meningkatkan kemampuan observasi",
    "harus mendukung pembelajaran lintas mata pelajaran",
    "harus membantu siswa belajar dari kesalahan",
    "harus menciptakan lingkungan belajar positif",
    "harus mengurangi rasa takut gagal",
    "harus mendorong keberanian mencoba",
    "harus mendukung pembelajaran reflektif",
    "harus memperkuat konsentrasi siswa",
    "harus mendukung pembelajaran visual",
    "harus mendukung pembelajaran praktis",
    "harus meningkatkan keterampilan sosial",
    "harus mendorong diskusi terbuka",
    "harus memberikan pengalaman belajar bermakna",
    "harus mendukung penggunaan sumber belajar beragam",
    "harus membantu siswa memahami konsep sulit",
    "harus meningkatkan keterlibatan emosional positif",
    "harus mendukung pembelajaran berbasis masalah",
    "harus memperkuat kemampuan bekerja sama",
    "harus membantu siswa mengatur waktu belajar",
    "harus meningkatkan kemandirian siswa",
    "harus mendukung pembelajaran berbasis minat",
    "harus meningkatkan rasa ingin tahu ilmiah",
    "harus memperkuat kemampuan berpikir logis",
    "harus mendukung pembelajaran yang adaptif",
    "harus meningkatkan kualitas interaksi di kelas",
    "harus mendukung pembelajaran berbasis eksplorasi",
    "harus membantu siswa menemukan solusi kreatif",
    "harus memperkuat keterampilan presentasi",
    "harus mendukung pembelajaran berbasis diskusi",
    "harus meningkatkan rasa keinginan belajar",
    "harus mendukung pembelajaran yang menyenangkan",
    "harus memperkuat keterampilan membaca",
    "harus memperkuat keterampilan menulis",
    "harus mendukung pembelajaran berbasis proyek nyata",
    "harus meningkatkan kemampuan refleksi kritis",
    "harus mendukung pembelajaran berbasis teknologi secara bijak",
    "harus memperkuat hubungan guru dan siswa",
    "harus mendukung pembelajaran berkelanjutan",
    "harus meningkatkan rasa pencapaian siswa",
    "harus mendukung pembelajaran yang inklusif secara budaya",
    "harus memperkuat rasa tanggung jawab sosial",
    "harus mendukung pembelajaran berbasis komunitas",
    "harus meningkatkan rasa percaya pada proses belajar",
    "harus mendukung pembelajaran yang berpusat pada siswa",
    "harus menciptakan pengalaman belajar yang bermakna dan positif"
];

let currentIdea = "";

function rand(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function clearInput() {
    document.getElementById("materi").value = "";
    document.getElementById("whatever").checked = true;
    document.getElementById("whatever_ifp").checked = true;
    document.getElementById("detila").checked = true;
    generateIdea();
}

function googleIt() {
    let text = document.getElementById("idea").innerText;
    let detil = document.querySelector('input[name="detil"]');
    if (detil.checked == true) {
        detil = detil.value;
    } else {
        detil = "ringkas";
    }

    let practiceType = document.querySelector('input[name="practice"]');
    if (practiceType.checked == true) {
        practiceType = practiceType.value;
    } else {
        practiceType = "";
    }
    if (practiceType === "BestPractice") {
        text = "kamu adalah guru senior dengan pengalaman luas dalam menyusun pembelajaran yang menyenangkan, berkesadaran dan bermakna. tugasmu sekaarang adalah membuat " + practiceType + " secara " + detil + " kerangka pembelajaran dengan ide : " + text;
        console.log(text);
    } else if (practiceType === "CommonPractice") {
        text = "kamu adalah guru senior dengan pengalaman luas dalam menyusun pembelajaran yang menyenangkan, berkesadaran dan bermakna. tugasmu sekaarang adalah membuat secara " + detil + " pembelajaran dengan ide : " + text + ", dengan alat dan bahan pembelajaran yang mudah ditemukan di sekitar rumah/ sekolah, susun langkah-langkah pembelajaran yang sederhana dan mudah diikuti.";
    } else {
        text = "kamu adalah guru senior dengan pengalaman luas dalam menyusun pembelajaran yang menyenangkan, berkesadaran dan bermakna. tugasmu sekaarang adalah membuat secara " + detil + " kerangka pembelajaran dengan ide : " + text;
    }
    let ifp = document.querySelector('input[name="ifp"]');
    if (ifp.checked == true) {
        ifp = ifp.value;
    } else {
        ifp = "";
    }
    if (ifp === "ifp") {
        text += ".Manfaatkan penggunaan Interactive Flat Panel (IFP) untuk mendukung pemahaman siswa dan meningkatkan keterlibatan siswa.";
    } else if (ifp === "nonifp") {
        text += ".Fokuskan pada metode pembelajaran yang tidak bergantung pada teknologi, tetapi tetap efektif dan menyenangkan untuk siswa.";
    }
    window.open("https://www.google.com/search?q=" + encodeURIComponent(text), "_blank");
}

function randomizeIdea() {
    const materi = document.getElementById("materi").value;
    const base = rand(baseIdeas);
    const twist = rand(twists);
    const tek = rand(teknik);
    const constraint = rand(constraints);
    if (materi !== "") {
        return `Belajar materi ${materi}, tapi ${twist} dengan ${tek} yang ${constraint}`;
    } else {
        return `Belajar materi ${base}, tapi ${twist} dengan ${tek} yang ${constraint}`;
    }
}

const select = new TomSelect('#dynamic', {
    maxItems: 1,
    placeholder: "Riwayat prompt yang sudah digenerate",
    render: {
        item: function (data, escape) {
            // Return an empty string or a custom static label instead of data.text
            return '<div style="color: grey;">Riwayat prompt yang sudah digenerate</div>';
        }
    }
});

function addselect(values, texts) {
    select.addOption({ value: values, text: texts });
}


function generateIdea() {
    document.getElementById("idea_container").style.display = "block";
    //mengganti isi ide tiap 100 mili detik selama 3 detik untuk memberikan efek loading
    let count = 0;
    const interval = setInterval(() => {
        document.getElementById("idea").innerHTML = randomizeIdea();
        count += 1;
        if (count >= 10) {
            clearInterval(interval);
            addselect(document.getElementById("idea").innerText, document.getElementById("idea").innerText);
        }
    }, 50);
}

document.addEventListener("DOMContentLoaded", function () {
    generateIdea();
});

const selectElement = document.querySelector('#dynamic');
selectElement.addEventListener('change', (event) => {
    // Access the value of the selected option
    const selectedText = event.target.options[event.target.selectedIndex].text;
    document.getElementById("idea").innerText = event.target.value;
});

